#include "app.h"

App &App::instance() {
    static App singleton;
    return singleton;
}

App::App() { //generated by quick-fix from server/app.h:10

}

App::~App() { //generated by quick-fix from server/app.h:12

}
